name: CI

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  HOME: ${{ github.workspace }}
on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@main

    # - name: Set HOME environment variable
    #   run: echo "HOME=$(echo $GITHUB_WORKSPACE)" >> $GITHUB_ENV

    - name: Use Go stable version
      uses: actions/setup-go@main
      with:
        go-version: 'stable'
