# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Reproduce Error-448

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  HOME: /home/runner/work/
jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: 'stable'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
