name: Go Workflow

on:
  push:
    branches: [ 476-Test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.x

    - name: Download dependencies
      run: go mod download

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: /home/runner/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check Go version
      run: go version

    - name: Build
      run: go build -v ./...

